[package]
name = "program-nautilus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
nautilus = { path = "../../../../solana", version = "0.0.1" }

[nautilus]
idl-dir = "./target/idl"
py-dir = "./target/idl/py"
ts-dir = "./target/idl/ts"